[build]
command = "npm install"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/api/health"

[[services]]
name = "backend"
source = "Dashboards/backend"

[environments.production.source]
repo = "shyukii/DCSP-Team-2"
branch = "main"
