[build]
command = "cd Dashboards/backend && npm install"

[deploy]
startCommand = "cd Dashboards/backend && node server.js"
healthcheckPath = "/api/health"

[environments.production.source]
repo = "shyukii/DCSP-Team-2"
branch = "main"
